myblog/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [path('', views.PostView.as_view()),
               path('weather/', views.index),
               path('<int:pk>/', views.PostDetail.as_view()),
               path('review/<int:pk>/', views.AddComments.as_view(), name='add_comment')]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from blog.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

handler404 = page_not_found

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField('Title', max_length=100)
    description = models.TextField('Text')
    author = models.CharField('Name', max_length=100)
    date = models.DateField('Date')
    img = models.ImageField('Img', upload_to='image/%Y')


    def __str__(self):
        return f'{self.title}, {self.author}'


class Comments(models.Model):
    email = models.EmailField()
    name = models.CharField("Name", max_length=50)
    text_comments = models.TextField('Text', max_length=2000)
    post = models.ForeignKey(Post, verbose_name='Publication', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}, {self.post}'

myblog/blog/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from .models import Post
from .form import CommentsForm
from django.http import HttpResponseNotFound
import requests


class PostView(View):
    def get(self, request):
        posts = Post.objects.all()
        return render(request, 'blog/blog.html', {'post_list': posts})


class PostDetail(View):
    def get(self, request, pk):
        post = Post.objects.get(id=pk)
        return render(request, 'blog/blog_detail.html', {'post': post})


class AddComments(View):
    def post(self, request, pk):
        form = CommentsForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.post_id = pk
            form.save()
        return redirect(f'/{pk}')


def index(request):
    city = 'Obinitsa'
    if request.method == 'POST':
        i = request.POST
        city = i['city']
    try:
        params = {'q': city, 'units': 'metric', 'lang': 'en', 'appid': '1912624fd49c501f2986b6ff90fd4a0b'}
        response = requests.get(f'https://api.openweathermap.org/data/2.5/weather', params=params)
        if not response:
            raise
        res = response.json()
        city_info = {'city': city, 'temp': round(res['main']['temp']), 'icon': res['weather'][0]['icon'], 'x': res['weather'][0]['description']}
    except:
        raise
    context = {'info': city_info}

    return render(request, 'blog/weather.html', context)


def page_not_found(request, exception):
    return HttpResponseNotFound('<h1>Такой страницы нет</h1>')

myblog/templates/blog/blog.html
{% load static %}
<html >
<head>
	<title>My Blog</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />

	<link rel="shortcut icon" href="css/images/favicon.ico" />

</head>
<body>
<div class="shell">
	<div class="border">

		<div id="navigation">
			<ul>
			    <li><a href="/" class="active">Home</a></li>
			    <li><a href="/admin">Log in</a></li>
			    <li><a href="/weather">Weather</a></li>
			</ul>
		</div>

		<div id="main">
			<div id="content" class="left">
				
				<div class="projects">
					<h3>Articles</h3>
					{% for post in post_list %}
					<div class="item">
						<div class="image left">
							<a href="#"><img src="{{ post.img.url }}" width="200px" /></a>
						</div>
						<div class="text left">
							<h4><a href="{{ post.id }}">{{ post.title }}</a></h4>
							<p>{{ post.description }}</p>
							<p>Autor: {{ post.author }}</p>
						</div>
						<div class="cl">&nbsp;</div>
					</div>
					{% endfor %}
				</div>
			</div>
			
			<div class="cl">&nbsp;</div>
		</div>
		

	</div>
	
	<div id="footer">
		<p class="copy right">Copyright &copy;  2022 </p>
	</div>
</div>
</body>
</html>

myblog/templates/blog/blog_detail.html
{% load static %}
<html xmlns="http://www.w3.org/1999/html">
<head>
	<title>My Blog</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />

	<link rel="shortcut icon" href="css/images/favicon.ico" />

</head>
<body>
<div class="shell">
	<div class="border">

		<div id="navigation">
			<ul>
			    <li><a href="/" class="active">Home</a></li>
			    <li><a href="/admin">Log in</a></li>
				<li><a href="/weather">Weather</a></li>
			</ul>
	    </div>

		<div id="main">
			<div id="content" class="left">

				<div class="projects">
					<h3>{{ post.title }}</h3>
                    <p align="center">
                        <img src="{{ post.img.url }}" width="50%"/>
                    </p>

					<div class="item">
						<div class="text left">

							<p>{{ post.description }}</p>
							<p>Autor: {{ post.author }}</p>
						</div>
						<div class="cl">&nbsp;</div>
					</div>
				</div>
			</div>
			<div class="form-comment">
				<h3>Write a comment</h3>
			<div>
			<form action="{% url 'add_comment' post.id %}" method="post">
				{% csrf_token %}
				<div>
			        <label>Your comment</label>
			        <textarea name="text_comments"></textarea>
				</div>
				<div>
			        <label>Name *</label>
			        <input type="text" name="name">
				</div>
				<div>
			        <label>Email *</label>
			        <input type="email" name="email">
				</div>
				<div><input type="submit" value="Send" /></div>
			</form>
		</div>
	</div>
    <div>
		{% for comment in post.comments_set.all %}
		<div class="view-comment">
			<h4>{{ comment.name }}</h4>
			<p>
				{{ comment.text_comments }}
			</p>
		</div>
		{% endfor %}
	</div>
</div>
	<div id="footer">
		<p class="copy right">  2023 </p>
	</div>
</div>
</body>
</html>

myblog/templates/blog/weather.html
{% load static %}
<html >
<head>
	<title>Weather</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />

	<link rel="shortcut icon" href="css/images/favicon.ico" />

</head>
<body>
<div class="shell">
	<div class="border">

		<div id="navigation">
			<ul>
			    <li><a href="/" class="active">Home</a></li>
			    <li><a href="/admin">Log in</a></li>
			    <li><a href="/weather">Weather</a></li>
			</ul>
		</div>

		<div id="main">
			<div id="content" class="left">

				<div class="projects">
					<h3>Weather today</h3>

					<div class="alert alert-danger">
						<b>City:</b> {{ info.city }}<br>
						<b>Temperature: </b> {{ info.temp }}<sup>o</sup> {{ info.x }}<br>
						<img src="http://openweathermap.org/img/w/{{ info.icon }}.png" alt="Фото погоды" class="img-thumbnail">
                    <form action="" method="post">
						{% csrf_token %}
						<label for="city"><b>Weather in your city </b></label>
						<input type="text" id="city" class="form-control" name="city" placeholder="enter city">
						<input type="submit" name="send" value="Узнать" class="mt-2 btm btn-danger">

					</form>

					</div>

				</div>
			</div>

			<div class="cl"></div>
		</div>


	</div>

	<div id="footer">
		<p class="copy right">Copyright &copy;  2023 </p>
	</div>
</div>
</body>
</html>